/* RAVAN AI v15 — substantial onboarding layout redesign */
(function(){
'use strict';
const css = String.raw`
:root{--r15-max:1380px;--r15-inner:1180px;--r15-purple:#5b47c7;--r15-purple-2:#755ee0;--r15-line:#e3e6f0;--r15-text:#24283a;--r15-muted:#767d91;--r15-card:#ffffff;--r15-soft:#f7f8fc}
html,body{background:#f3f5fb!important}
.r11-gate{padding:22px 28px 34px!important;align-items:flex-start!important;justify-content:center!important;background:radial-gradient(circle at 88% -5%,rgba(111,91,218,.16),transparent 28%),radial-gradient(circle at 8% 105%,rgba(54,122,246,.09),transparent 25%),#f3f5fb!important}
.r11-shell{width:min(var(--r15-max),calc(100vw - 56px))!important;margin:0 auto!important;background:transparent!important;border:0!important;border-radius:0!important;box-shadow:none!important;overflow:visible!important}
.r11-head{padding:22px 28px!important;min-height:86px!important;border-radius:22px!important;box-shadow:0 16px 42px rgba(70,53,150,.18)!important;background:linear-gradient(135deg,#4937b0 0%,#634dd0 52%,#765fe0 100%)!important}
.r11-brand h1{font-size:28px!important;line-height:1.35!important;margin:0 0 5px!important}.r11-brand p{font-size:12.5px!important;line-height:1.8!important;max-width:900px!important}.r11-mark{font-size:11px!important;padding:7px 11px!important}.r11-body{padding:16px 0 0!important;min-height:0!important}
.r11-stepbar{width:min(var(--r15-inner),100%)!important;max-width:none!important;margin:0 auto 14px!important;padding:8px!important;display:grid!important;grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:8px!important;background:#fff!important;border:1px solid var(--r15-line)!important;border-radius:16px!important;box-shadow:0 8px 24px rgba(42,39,78,.05)!important}
.r11-stepchip{min-height:52px!important;padding:9px 12px!important;border-radius:11px!important;border-color:transparent!important;background:#f7f8fc!important;font-size:12px!important;font-weight:700!important}.r11-stepchip.active{background:#f1eeff!important;border-color:#d8d1ff!important;color:#3f336f!important}.r11-stepchip.done{background:#eefaf6!important;border-color:#caeadd!important}.r11-stepchip b{width:30px!important;height:30px!important;min-width:30px!important;border-radius:9px!important;font-size:12px!important}
.r11-section.active{display:block!important;width:min(var(--r15-inner),100%)!important;max-width:none!important;margin:0 auto!important;padding:22px 24px 20px!important;box-sizing:border-box!important;background:#fff!important;border:1px solid var(--r15-line)!important;border-radius:20px!important;box-shadow:0 12px 34px rgba(42,39,78,.065)!important}.r11-section:not(.active){display:none!important}.r11-section>.r11-title{width:100%!important;max-width:none!important;margin:0 0 14px!important;padding:0!important;align-items:center!important}.r11-title h2{font-size:20px!important;line-height:1.5!important;margin:0 0 4px!important;color:var(--r15-text)!important}.r11-title p{font-size:11.5px!important;line-height:1.8!important;max-width:920px!important;color:var(--r15-muted)!important}
.r112-role-box,.r115-task-box{width:100%!important;max-width:none!important;margin:0!important;padding:16px!important;box-sizing:border-box!important;border:1px solid #e7e9f2!important;border-radius:15px!important;background:#f9faff!important;box-shadow:none!important}.r112-role-label,.r115-task-label{font-size:12.5px!important;margin:0 0 7px!important;color:#34394d!important}.r112-role-input,.r115-task-input{min-height:48px!important;font-size:13px!important;background:#fff!important;border-radius:11px!important}.r112-role-note,.r115-task-note{margin:8px 2px 0!important;font-size:10.5px!important;line-height:1.75!important;color:#7b8294!important}.r112-role-next{min-height:46px!important;margin-top:10px!important;border-radius:11px!important;font-size:13px!important;box-shadow:0 8px 18px rgba(91,71,199,.16)!important}
.r112-combo-menu.open,.r115-task-menu.open{display:grid!important;grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:5px!important;max-height:292px!important;padding:6px!important;margin-top:7px!important;overflow-y:auto!important;border-radius:12px!important;background:#fff!important;box-shadow:0 8px 22px rgba(42,38,80,.07)!important}.r112-role-option,.r115-task-option{min-width:0!important;padding:8px 9px!important;gap:8px!important;border:1px solid transparent!important}.r112-role-option:hover,.r112-role-option.active,.r115-task-option:hover,.r115-task-option.active{border-color:#ddd6ff!important;background:#f5f2ff!important}.r112-role-option .ico,.r115-task-option .ico{width:31px!important;height:31px!important;font-size:14px!important}.r112-role-option b,.r115-task-option b{font-size:12px!important}.r112-role-option small,.r115-task-option small{font-size:9.6px!important;line-height:1.5!important}
.r11-saved{width:100%!important;max-width:none!important;margin:12px 0 0!important;padding:10px 12px!important;box-sizing:border-box!important;border:1px dashed #dfe2ec!important;border-radius:12px!important;background:#fbfcfe!important;display:flex!important;align-items:center!important;gap:10px!important;box-shadow:none!important}.r11-saved h3{font-size:10.5px!important;margin:0!important;color:#737a8c!important;white-space:nowrap!important}.r11-pills{gap:6px!important;min-width:0!important}.r11-pill{font-size:10px!important;padding:5px 9px!important;background:#fff!important}.r11-saved.r15-empty{display:none!important}
.r11-ai-grid{max-width:none!important;width:100%!important;grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:9px!important}.r11-ai{padding:14px!important;border-radius:13px!important;min-height:92px!important}.r11-rec,.r11-actions{max-width:none!important;width:100%!important;box-sizing:border-box!important}.r11-actions{margin-top:14px!important;padding-top:13px!important}
.r11-ws-shell{max-width:1380px!important;padding:18px 24px 28px!important}.r11-ws-top{border-radius:20px!important;padding:18px 22px!important}.r11-ws-main{grid-template-columns:250px minmax(0,1fr)!important;gap:14px!important;margin-top:14px!important}.r11-ws-side,.r11-ws-content{border-radius:16px!important}.r11-ws-content{padding:18px!important}.r11-fields{gap:10px!important}.r11-field{padding:12px!important;border-radius:12px!important}
@media(max-width:1100px){.r11-gate{padding:14px!important}.r11-shell{width:min(100%,980px)!important}.r11-head{border-radius:18px!important}.r112-combo-menu.open,.r115-task-menu.open{grid-template-columns:repeat(2,minmax(0,1fr))!important}}
@media(max-width:760px){.r11-gate{padding:8px!important}.r11-shell{width:100%!important}.r11-head{padding:17px!important;min-height:0!important;border-radius:16px!important;flex-direction:column!important;align-items:flex-start!important}.r11-brand h1{font-size:22px!important}.r11-brand p{font-size:10.5px!important}.r11-stepbar{gap:5px!important;padding:6px!important;border-radius:13px!important}.r11-stepchip{min-height:44px!important;padding:6px 7px!important;font-size:9.5px!important;gap:5px!important}.r11-stepchip b{width:24px!important;height:24px!important;min-width:24px!important;font-size:10px!important}.r11-section.active{padding:16px!important;border-radius:16px!important}.r11-title h2{font-size:17px!important}.r11-title p{font-size:10px!important}.r112-role-box,.r115-task-box{padding:12px!important}.r112-combo-menu.open,.r115-task-menu.open{grid-template-columns:1fr!important;max-height:230px!important}.r11-saved{align-items:flex-start!important;flex-direction:column!important;gap:6px!important}.r11-ai-grid{grid-template-columns:1fr!important}.r11-ws-main{grid-template-columns:1fr!important}.r11-ws-side{position:static!important}}
`;
function installStyles(){const old=document.getElementById('ravanUiV14');if(old)old.remove();if(document.getElementById('ravanUiV15'))return;const s=document.createElement('style');s.id='ravanUiV15';s.textContent=css;document.head.appendChild(s);document.documentElement.dataset.ravanUi='15'}
function tidySaved(){const wrap=document.getElementById('r11SavedWrap');const pills=document.getElementById('r11SavedProfiles');if(!wrap||!pills)return;wrap.classList.toggle('r15-empty',pills.children.length===0)}
function boot(){installStyles();tidySaved();const pills=document.getElementById('r11SavedProfiles');if(pills){new MutationObserver(tidySaved).observe(pills,{childList:true,subtree:true})}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();